apiVersion: apps/v1
kind: Deployment
metadata:
  name: bms-app
  labels:
    app: bms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bms
  template:
    metadata:
      labels:
        app: bms
    spec:
      containers:
        - name: bms-container
          image: 950174293211.dkr.ecr.ap-southeast-2.amazonaws.com/bms:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
